Name="Userspace Programs"
Vendor="Pindorama"
Description="Copacabana general userspace programs"
Version="0.5"
Maintainer="Luiz Antônio Rangel"
Hotline="luiz.antonio.rangel@outlook.com.br"

; TODO: Make it as a section.
; [heirloom-ng]
HeirloomNG_Version=250220

; [mico]
